VERSION = "2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
SIGNING_KEY = "GBQVKVFXHM3SLYLSIFUNDI2VALQPGOEHLDJ3Z3OLHXS4PK4GN2FSLKLY"

ACCOUNTS = [
    "GBQVKVFXHM3SLYLSIFUNDI2VALQPGOEHLDJ3Z3OLHXS4PK4GN2FSLKLY",
    "GBSP6Z42G7KWTKK2SK7CCGTNZOUC4N5OI3JJAJ35ML7DMPAVG3BRM2ZK",
    "GAQSBA75ZAJT4NY6JIL7XIBRT6VVVHXDFQ3NLHS5GKTLCKLOVAGLVYQ5",
    "GCNBBQLCRN7AHIQ72LRQU24UZNS5ZCIL7HUXPBA326UUMTRHT55OA5ET"
]

[DOCUMENTATION]
ORG_NAME = "Cody Cordova"
ORG_DBA = "CODY Token"
ORG_URL = "https://www.codytoken.com"
ORG_LOGO = "https://codytoken.com/cclogo.png"
ORG_DESCRIPTION = "CODY Token is a Stellar-based utility token created by music artist Cody Cordova. It supports merch, tickets, games, and digital community tools."
ORG_PHYSICAL_ADDRESS = "Los Angeles, CA"
ORG_PHONE_NUMBER = "+18186997275"
ORG_KEYBASE = "realcodycordova"
ORG_TWITTER = "realcodycordova"
ORG_GITHUB = "codycordova"
ORG_OFFICIAL_EMAIL = "mgmt@codycordova.com"

[[PRINCIPALS]]
name = "Cody Cordova"
email = "mgmt@codycordova.com"
keybase = "realcodycordova"
twitter = "realcodycordova"
github = "realcodycordova"

[[CURRENCIES]]
code = "CODY"
issuer = "GAW55YAX46HLIDRONLOLUWP672HTFXW5WWTEI2T7OXVEFEDE5UKQDJAK"
display_decimals = 2
name = "CODY Token"
desc = "The official utility token for multimedia artist Cody Cordova — used for merch, tickets, gaming rewards, and community interaction."
conditions = "Total supply capped at 444,444,444,444 CODY. Only 1,016 tokens are currently in circulation to test market behavior and liquidity in a research-backed rollout."
image = "https://codytoken.com/cclogo.png"
fixed_number = 444444444444
price_api = "https://codytoken.com/api/price"
price_source = "CODY Token Official API"
is_asset_anchored = false
status = "live"
