VERSION="2.0.0"

NETWORK_PASSPHRASE = "CODY Token ; June 2023"
SIGNING_KEY="GBQVKVFXHM3SLYLSIFUNDI2VALQPGOEHLDJ3Z3OLHXS4PK4GN2FSLKLY"
ACCOUNTS = [ "GBQVKVFXHM3SLYLSIFUNDI2VALQPGOEHLDJ3Z3OLHXS4PK4GN2FSLKLY",
    "GBSP6Z42G7KWTKK2SK7CCGTNZOUC4N5OI3JJAJ35ML7DMPAVG3BRM2ZK",
    "GAQSBA75ZAJT4NY6JIL7XIBRT6VVVHXDFQ3NLHS5GKTLCKLOVAGLVYQ5",
    "GCNBBQLCRN7AHIQ72LRQU24UZNS5ZCIL7HUXPBA326UUMTRHT55OA5ET"]

[DOCUMENTATION]
ORG_NAME="Cody Cordova"
ORG_URL="https://www.codycordova.com"
ORG_LOGO="https://www.codycordova.com/uploads/9/7/2/8/97282376/cody-token-logo_orig.png"
ORG_DESCRIPTION="Music Artist based in Los Angeles, CA."
ORG_PHYSICAL_ADDRESS="Los Angeles, CA"
ORG_PHONE_NUMBER="+18186997275"
ORG_KEYBASE="realcodycordova"
ORG_TWITTER="realcodycordova"
ORG_GITHUB="codycordova"
ORG_OFFICIAL_EMAIL="mgmt@codycordova.com"

[[PRINCIPALS]]
name="Cody Cordova"
email="mgmt@codycordova.com"
keybase="realcodycordova"
twitter="realcodycordova"
github="realcodycordova"

[[CURRENCIES]]
code="CODY"
issuer="GAW55YAX46HLIDRONLOLUWP672HTFXW5WWTEI2T7OXVEFEDE5UKQDJAK"
display_decimals=2
name="CODY Token"
desc="The official token for Tech House artist Cody Cordova."
conditions="There will only ever be 444 billion CODY tokens in existence."
image="https://www.codycordova.com/uploads/9/7/2/8/97282376/cody-token-logo_orig.png"
fixed_number=444444444444
is_asset_anchored=true
anchor_asset_type="crypto"
anchor_asset="XLM"

# The following CURRENCIES entry for USDC is included for reference purposes.
# USDC is managed by Centre.io, and its `home_domain` is set to "centre.io."
# This asset is included to provide a reference for the USD equivalent of CODY Token.

[[CURRENCIES]]
code="USDC"
issuer="GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN"
is_asset_anchored=true
anchor_asset_type="fiat"
anchor_asset="USD"
attestation_of_reserve="https://www.centre.io/usdc-transparency"
redemption_instructions="Redeemable through a Circle account at https://circle.com"
name="USD Coin"
desc="USDC is a fully collateralized US Dollar stablecoin, based on the open-source fiat stablecoin framework developed by Centre."
image="https://www.centre.io/images/usdc/usdc-icon-86074d9d49.png"
